### ISSUE TITLE
Redirect to Redirect_URI Broken Due to Incorrect Character in the URL

### ISSUE THREAD

**Issue by wedmunds** [department-of-veterans-affairs/vets-api-clients#105]
#97  APIs affected (if applicable)

Developer Veteran Authentication API

## What I expected to happen

1. Authorize and receive access_token
2. Redirect user for OAuth login
3.  User should be redirected back to the specified request_uri URL

## What actually happened

An error in the URL where a # is being used incorrectly instead of a ? is causing the redirect from dev-api.va.gov/oauth2/redirect to the redirect_uri specified during authorization to break and output "An unknown error has occurred."

After the customer approves access to the veteran status, they're redirected to a url similar to the one below (I've removed much of the params to shorten it)

https://dev-api.va.gov/oauth2/redirect#access_token=eyJraWQiOiJUdWZhS3pD... 

There is a # after /oauth2/redirect and before access_token, this needs to be a ?, not a # 

When the full URL is copied and the # replaced with a ? it redirects back to the request_uri as it should.

## Severity of the issue

- [ x ] High severity: Blocking work
- [ ] Medium severity: Not blocking work, but needs attention
- [ ] Low severity: Needs attention in a timely manner

- [ ] I am unable to use the API
- [x ] I was able to use the API, but am not getting the results I expected
- [ ] I was able to workaround the issue
      

## Steps to reproduce

1. Authorize app access to veteran status using one of the id.me test accounts.
2. Wait for the attempted redirect back to the request_uri specified during authorization.

**Comment by dvogel** [comment]
@wedmunds you should be able to get the behavior you're seeing by specifying `response_type=code` and `response_mode=query` in your initial authorize request.

**Comment by wedmunds** [comment]
hey Drew, thanks for the quick reply.  I updated those variables and 
everything does seem to be working now.  Sweet, thanks :)

**Comment by ryanlink** [comment]
Glad to hear it, thanks @wedmunds .  We received your email as well and will be in touch about your production access request.

Ryan Link
Customer Success Manager & Developer Support Lead
VA Lighthouse API Program
api@va.gov

Visit developer.va.gov for more on the VA API Program
Visit valighthouse.statuspage.io to subscribe to API status alerts
Visit GovDelivery to subscribe to the Lighthouse API newsletter

**Comment by beaugrantham-va** [comment]
Closing stale issues.
