### ISSUE TITLE
Facilities/All throws 500

### ISSUE THREAD

**Issue by gclapp** [department-of-veterans-affairs/vets-api-clients#13]
Any calls to facilities/all throws a 500 error. Calls to individual locations continue to work. This has happened 5-6 times over 24 hours, so doubtful it's specific to server state. 

https://dev-api.vets.gov/services/va_facilities/v0/facilities/all

**Headers**:
apikey: <not shown, but works with other calls>

**Response:**
```
{
    "errors": [
        {
            "title": "Internal server error",
            "detail": "Internal server error",
            "code": "500",
            "status": "500"
        }
    ]
}
```

**Comment by patrickvinograd** [comment]
Thank you for reporting this issue, we are looking into it now.

**Comment by patrickvinograd** [comment]
This issue is fixed, confirmed both csv and geojson bulk downloads are working correctly. Thanks for your patience.
