### ISSUE TITLE
Change "long" to "lng" or "longitude"

### ISSUE THREAD

**Issue by gclapp** [department-of-veterans-affairs/vets-api-clients#15]
I know the last thing you want to do is change the API signature, but making it "lat" and "long" is a bummer. (Specifically Facility Attributes).  It really makes marshalling Java objects a pain. I'm sure anyone in a typed language is going to feel similarly. 

Either the google maps (lat/lng) (see below) or HCA methods (they use latitude and longitude spelled out...but they also quote the values, so  <shrug emoji>)  would be greatly appreciated and are probably very familiar to your user base.  I could also see lots of reasons for you to DNF this. Thanks for considering. 

```
 "formatted_address" : "1600 Amphitheatre Parkway, Mountain View, CA 94043, USA",
         "geometry" : {
            "location" : {
               "lat" : 37.4224764,
               "lng" : -122.0842499
            },
            "location_type" : "ROOFTOP",
            "viewport" : {
               "northeast" : {
                  "lat" : 37.4238253802915,
                  "lng" : -122.0829009197085
               },
               "southwest" : {
                  "lat" : 37.4211274197085,
                  "lng" : -122.0855988802915
               }
            }
```

**Comment by edpaget** [comment]
I'd recommend using the GeoJSON responses by making your requests with a `Accept: application/vnd.geo+json` as a workaround for now since that returns lat/lng as a two element array which will hopefully make marshaling easier. 

Since this would a breaking change to the API, I'm not sure we can commit to making this change in the near future, though I agree it would make things easier for Java developers.

**Comment by gclapp** [comment]
Totally fair. It can be worked around, I would certainly consider this very very low urgency.

**Comment by ryanlink** [comment]
@gclapp This was resolved in the release of June 17, 2019.  https://github.com/department-of-veterans-affairs/vets-api/pull/3084

Cheers!

Ryan Link
Customer Success Manager
API Support Lead, Lighthouse | VA API Program
api@va.gov
Visit developer.va.gov for more on the VA API Program

NEW ->  Monitor API status and get outage notifications: valighthouse.statuspage.io

**Comment by ryanlink** [comment]
Deleted my previous comment; this has only been resolved for the `/nearby` endpoint.  The other endpoints remain v0 and have not incorporated this change yet.

**Comment by beaugrantham-va** [comment]
Closing stale issues.
