### ISSUE TITLE
API returns incorrect address

### ISSUE THREAD

**Issue by johnfedwards** [department-of-veterans-affairs/vets-api-clients#165]
## VA Lighthouse API Bug Report

⚠️ Please read before submitting: As this is a public forum, please do not include any sensitive information (such as your VA API OAuth Client ID, VA API OAuth Client Secret, VA API key, Name, Address, Phone Number, Social Security Number, Medical Record Number, etc). For test apps, please make sure you are using your registered redirect URL, not the URL provided in the example.

## APIs affected (if applicable)

VA Facilities API

## API version (if applicable)

v0

## What I expected to happen

1. https://www.va.gov/find-locations/facility/vha_676GD returns the correct address for the facility
2. https://www.tomah.va.gov/locations/WisconsinRapids.asp displays incorrect address after calling API /facilities/{id} method with vha_676GD
3. https://www.tomah.va.gov/locations/index.asp displays incorrect address after calling API /facilities method when ID list include vha_676GD

## What actually happened

I assumed the facilities on www.va.gov/find-locations used the API, yet the address displayed there for facility vha_676GD do not match the address returned by the API

## Severity of the issue

Medium severity

- [ ] High severity: Blocking work
- [X] Medium severity: Not blocking work, but needs attention
- [ ] Low severity: Needs attention in a timely manner

- [ ] I am unable to use the API
- [X] I was able to use the API, but am not getting the results I expected
- [ ] I was able to workaround the issue
      

## Steps to reproduce

1. https://www.va.gov/find-locations/facility/vha_676GD
2. https://www.tomah.va.gov/locations/WisconsinRapids.asp
3. https://www.tomah.va.gov/locations/index.asp

Address on #1 does not match address displayed on #2 and #3 after they called the API.  I assumed #1 also used the API

**Comment by ryanlink** [comment]
Hi John,

Thanks for letting us know.  This should be resolved now.  

It appears that a load balancer for the facility locator was getting info from two different datasources (CDW and geoBISL).  We were getting different results on subsequent page loads of https://www.va.gov/find-locations/facility/vha_676GD - sometimes 700 and sometimes 555.  

Our database did not get this update until we forced a rerun of an ETL process which pulls from another database and had failed partway through. How recently did this address change?  

The load balancer has been removed from the equation now, I believe, and we are implementing monitoring to detect ETL failures in the future.

Cheers,

Ryan Link
Customer Success Manager & Developer Support Lead
VA Lighthouse API Program
api@va.gov
