### ISSUE TITLE
TLS authentication requirements and correct end point for Address Validation sandbox service?

### ISSUE THREAD

**Issue by markkvba** [department-of-veterans-affairs/vets-api-clients#169]
Hello Api Team,

While waiting for the apiKey provisioning (seperate email sent..), could you please let me know of if you require MTLS for either the sandbox or production end point for the address validation service. I need to know this as soon as possible as our times line is pretty urgent to migrate to this service.

Could confirm that information I receveived for the  correct endpoint for sandbox as the error is 404. The request contains the apiKey and client cert. apiKey maybe not active? Is that the expected response if that's the case?

https://sandbox-api.va.gov/services/address_validation/address/v1/cityStateProvince/{postCode}
{
    "message": "no Route matched with those values"
}

Thank you,
Mark Komosa

**Comment by ryanlink** [comment]
Hi @markkvba - as I mentioned in reply to your email, standard TLS should suffice.  We are working on the 404 error, though. Not sure yet what's causing that.

**Comment by ryanlink** [comment]
There’s an extra `/address` in yours that is not needed:

https://sandbox-api.va.gov/services/address_validation/v1/cityStateProvince/{postcode}
