### ISSUE TITLE
Data Inconsistency (Could be terminology only) 

### ISSUE THREAD

**Issue by gclapp** [department-of-veterans-affairs/vets-api-clients#17]
## APIs Affected

Facilities API (all implementation)

## Brief Summary 

When filtering by health, it claims certain organizations do not have urgent care, but they all have same-day primary care (?) which is not listed as a service. Is it safe to assume that "Primary Care" is the same as "Same Day Primary Care" - is there a "non-same day primary care?" - the services list only accounts for "Primary Care" but this press release makes it sound like they are synonymous.  (https://www.va.gov/opa/pressrel/pressrelease.cfm?id=3998)

Even more confusing...what's "primary_care_urgent" in the context of the satisfaction scores? Is that primary care...or urgent care...or really fast primary care :)

```
"satisfaction": {
"health": {
"primary_care_urgent": 0.92,
 "primary_care_routine": 0.89,
},
                    "effective_date": "2018-05-22"
                },
```

What is Urgent Care in that context? These seems to be VA-specific terminology but want to be sure I've got it right. 

This is *NOT* urgent. I'm just confused by the terminology and if I'm giving people the right information.  It does not prevent from using the API.

## Steps to Reproduce

API: https://dev-api.vets.gov/services/va_facilities/v0/facilities/all?type=health&healthservice=UrgentCare

Web:  https://www.accesstopwt.va.gov/Main/FindFacilities?LocationText=94087&Radius=50&SortOrder=0&UserLatitude=-1&UserLongitude=-1&SameDayServiceView=true

See slightly different results, would be nice to normalize or understand/document the difference. Thank you!

**Comment by edpaget** [comment]
Finally had a change to talk to another developer about what these mean. It seems that `primary_care_urgent` in the satisfaction ratings refers to walk-in non-specialist services. That service may or not be advertised by a particular facility as being urgent care, and it won't come up when filtering by urgent care if they don't. I believe this is the same as Same Day Primary Care as in the linked press release. Non-Same Day Primary Care would be pre-scheduled non-specialist appointments.

**Comment by gclapp** [comment]
Okay, I think I got it:

The satisfaction ratings are just for `primary_care_urgent `can be used in the same context of `urgent_care` - I shouldn't assume anything from there about service lines (which makes sense, could have an unrated service line).

Urgent care is "urgent care" - but all sites have same-day primary care
Primary care is same day (maybe super long wait) or, make an appointment

Is safe to assume the wait time for primary care is that only in the case you want to make an appointment for non-specialist non-same-day primary care? 

Also, I swear I'm not :trollface:

**Comment by edpaget** [comment]
Sorry didn't realize there was another question here. 

I believe that's correct.
