### ISSUE TITLE
Inconsistancy between facilities calls

### ISSUE THREAD

**Issue by gclapp** [department-of-veterans-affairs/vets-api-clients#18]
## APIs Affected

All Facility APIs 

## Explanation Feature

Right now the "specific" version of facilities returns one kind of object, but the "all" (and filtered) version returns another. This means that for the same API endpoint we end up having to marshal 

For example, calling:

https://dev-api.vets.gov/services/va_facilities/v0/facilities/all 

gives me a Boston Vet Center that looks like this:

```
{
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -71.0361051099999,
                    42.3445959000001
                ]
            },
            "properties": {
                "id": "vc_0101V",
                "name": "Boston Vet Center",
                "facility_type": "vet_center",
                "classification": null,
                "website": null,
                "address": {
                    "mailing": {},
                    "physical": {
                        "zip": "02210",
                        "city": "Boston",
                        "state": "MA",
                        "address_1": "7 Drydock Avenue",
                        "address_2": "Suite 2070",
                        "address_3": null
                    }
                },
                "phone": {
                    "main": "857-203-6461 x"
                },
                "hours": {
                    "friday": "800AM-600PM",
                    "monday": "800AM-700PM",
                    "sunday": "-",
                    "tuesday": "800AM-800PM",
                    "saturday": "-",
                    "thursday": "800AM-800PM",
                    "wednesday": "800AM-700PM"
                },
                "services": {},
                "satisfaction": {},
                "wait_times": {}
            }
        }
```
whereas calling the api for this facilty directly gives me this:

https://dev-api.vets.gov/services/va_facilities/v0/facilities/vc_0101V
```

{
    "data": {
        "id": "vc_0101V",
        "type": "va_facilities",
        "attributes": {
            "name": "Boston Vet Center",
            "facility_type": "vet_center",
            "classification": null,
            "website": null,
            "lat": 42.3445959000001,
            "long": -71.0361051099999,
            "address": {
                "mailing": {},
                "physical": {
                    "zip": "02210",
                    "city": "Boston",
                    "state": "MA",
                    "address_1": "7 Drydock Avenue",
                    "address_2": "Suite 2070",
                    "address_3": null
                }
            },
            "phone": {
                "main": "857-203-6461 x"
            },
            "hours": {
                "monday": "800AM-700PM",
                "tuesday": "800AM-800PM",
                "wednesday": "800AM-700PM",
                "thursday": "800AM-800PM",
                "friday": "800AM-600PM",
                "saturday": "-",
                "sunday": "-"
            },
            "services": {},
            "satisfaction": {},
            "wait_times": {}
        }
    }
}
```

**Differences include:**

1. It's called "_feature_" rather than "_data_" - normalize on one ("_Facility_") would be nice but as long as it's one or the other, I can make that facility on my side. Data seems more reasonable than feature, which makes no sense in the /all context (at least to me). 

2. Lat and Long are in different places with different structures and labels. Please use the labeled versions in the individual facility model. 

3. In the single-api return, it's called "_attributes_" but in the all return version it's called properties. No real care about which, but sure would like it to be one or the other. 

## Value Provided by Feature
The current system creates work and duplicate marshaling code for the API developer. It's a PIA and makes me want to wait for a future version.  I would expect /all or even a filtered version to return the same json objects, just filtered down based on the request, not a totally different object. 

If you agree I can break out each of the above listed differences as a bug report.
 
## Acceptance Criteria

Return the same object in both the /<facilityId> version for all & filtered versions. The version in /<facilityid> which is pretty clear and easy to use/convert from json to reasonable objects. 

Thank you.

**Comment by gclapp** [comment]
Is it possible that it's a problem with the accept header? 

When I use **application/json** explicitly, I get a 406 error ("The resource could not be returned in the requested format" whereas if I remove that, it will return the vnd.geo+json format.

It looks like:

(A) The default listed in the documentation (application/json) is not supported for the /all api? See documentation below
(B) The default is the geoJSON for any "all" requests

https://developer.va.gov/explore/facilities/docs/facilities
> Response Formats
> 
> Clients may request several response formats by setting the Accept header.
> 
> application/json - The default JSON response format complies with JSON API.
> application/vnd.geo+json - GeoJSON-compliant format, representing each facility as a Feature with a Point geometry.
> text/csv - Available for the bulk download operation only. Some structured fields are omitted from the CSV response.

**Comment by edpaget** [comment]
This works as intended. I will update the documentation to clarify that application/json is not an allowed media type for the `/all` endpoint. 

The `/all` endpoint will only return the set of data as [GeoJSON](http://geojson.org/) or CSV depending on the client's accept header, since it's just intended . The filterable endpoint will return [JSON API](http://jsonapi.org/) formatted data in the absence of a more specific Accept header. You can make requests to the fitlerable endpoint with a `Accept: application/vnd.geo+json` header and it will return data in a format consistent with the `/all` endpoint.

**Comment by gclapp** [comment]
Okay - few things:

Let me test the filtered version. I am 99% sure that even with the accept set to `application/json` it was returning GeoJSON. 

_Do you want me to open a separate issue for that if it indeed only returns GeoJSON?_ 

If you can fix the documentation, that's great. I'd love to understand why the `accept/json` is unsupported, as that seems like you are forcing extra work on the developer, but there's probably another reason I don't see. It is a separate endpoint at least. I also realize GitHub is not the place for that conversation, perhaps.

**Comment by gclapp** [comment]
Yeah, I forgot - the filtered facilities call does not work, that's why I ended up trying all. I will open a separate issue for that. Sorry that I forgot that rather important detail! I will link the bug here.

**Comment by edpaget** [comment]
Yeah if you'd open a separate ticket if it's returning GeoJSON formatted data by default on the filtered endpoint that is not the documented behavior. 

We don't really want people using the `/all` endpoint regularly is the main reason why it has different rules. As I mentioned it's only really intended for users that need full dataset for local caching or processing. If you're building an interactive application that is regularly making API calls you should always use with some kind of filtered call.
