### ISSUE TITLE
Sandbox Forms API - 500 Internal Error

### ISSUE THREAD

**Issue by sliaf** [department-of-veterans-affairs/vets-api-clients#181]
## VA Lighthouse API Bug Report

⚠️ Please read before submitting: As this is a public forum, please do not include any sensitive information (such as your VA API OAuth Client ID, VA API OAuth Client Secret, VA API key, Name, Address, Phone Number, Social Security Number, Medical Record Number, etc). For test apps, please make sure you are using your registered redirect URL, not the URL provided in the example.

## APIs affected (if applicable)

https://sandbox-api.va.gov/services/va_forms/v0/forms

## API version (if applicable)

Version 0.0.1

## What I expected to happen

1.  Send get request with apiKey to https://sandbox-api.va.gov/services/va_forms/v0/forms
2.  Request returns a list of all forms

## What actually happened
Request returns 500 internal server error, this started happening yesterday.  I have tested using curl and chrome.

## Severity of the issue

- [x] High severity: Blocking work
- [ ] Medium severity: Not blocking work, but needs attention
- [ ] Low severity: Needs attention in a timely manner

- [x] I am unable to use the API
- [ ] I was able to use the API, but am not getting the results I expected
- [ ] I was able to workaround the issue
      

## Steps to reproduce

1. Open Chrome 
2. Enter https://sandbox-api.va.gov/services/va_forms/v0/forms?apikey=XXX and replace XXX with your apiKey and hit enter
3. 500 internal server error is returned.

Alternatively you can execute with curl 
curl -X GET "https://sandbox-api.va.gov/services/va_forms/v0/forms" --header "apikey: XXX"

![image](https://user-images.githubusercontent.com/37052490/90638739-51914980-e1f3-11ea-81bf-116915d71dcc.png)
![image](https://user-images.githubusercontent.com/37052490/90638787-61109280-e1f3-11ea-9f9f-47890035501f.png)

**Comment by sliaf** [comment]
This is working now.

**Comment by ryanlink** [comment]
Thanks @sliaf - this was a glitch in deployment that was fixed almost immediately.  We appreciate you calling our attention to it.

Ryan Link
Customer Success Manager
VA Lighthouse API Program
developer.va.gov
