### ISSUE TITLE
Inconsistancy of data when "closed"

### ISSUE THREAD

**Issue by gclapp** [department-of-veterans-affairs/vets-api-clients#19]
## APIs Affected

Facilities API, V0

## Brief Summary 

Sometimes you use "-" for closed, other times you use the word "closed"

Example:

*VA Facility vba_343h*
```
 "hours": {
                    "Friday": "8:00AM-4:00PM",
                    "Monday": "8:00AM-4:00PM",
                    "Sunday": "Closed",
                    "Tuesday": "8:00AM-4:00PM",
                    "Saturday": "Closed",
                    "Thursday": "8:00AM-4:00PM",
                    "Wednesday": "8:00AM-4:00PM"
                },
```

compare that to *San Jose (vha_640BY)*

```
"hours": {
                    "Friday": "800AM-430PM",
                    "Monday": "800AM-430PM",
                    "Sunday": "-",
                    "Tuesday": "800AM-630PM",
                    "Saturday": "800AM-1200PM",
                    "Thursday": "800AM-430PM",
                    "Wednesday": "800AM-430PM"
                },
```

It appears that when it's a VBA, it's "closed" but when it's a VHA or other health-related facility, it's a "-"  -- I've not looked at every one, but looking at the following VBAs (vba_666, vha_610A4a, vha_610A4, vba_583) all use the "closed" and all the VHA's I looked at use "-" 

I did *not* look at all 400 VBA sites. That could be a red herring. 

## Severity of the Issue

It's a big pain in the butt, but it's not preventing me from moving forward, just more case statements and checking for results. 

## Steps to Reproduce

Call the API for the above examples...

**Comment by edpaget** [comment]
I'll add this to our roadmap. I agree this seems annoying.

**Comment by nfasulo** [comment]
The standardization of any casing of "closed" and "-" to "Closed" was deployed on February 13th.
