### ISSUE TITLE
Getting internal server error

### ISSUE THREAD

**Issue by Kanniga-Git** [department-of-veterans-affairs/vets-api-clients#191]
## VA Lighthouse API Bug Report

⚠️ Please read before submitting: As this is a public forum, please do not include any sensitive information (such as your VA API OAuth Client ID, VA API OAuth Client Secret, VA API key, Name, Address, Phone Number, Social Security Number, Medical Record Number, etc). For test apps, please make sure you are using your registered redirect URL, not the URL provided in the example.

## What I expected to happen

1. 
2. 
3. 

## Severity of the issue

- [ ] High severity: Blocking work
- [ ] Medium severity: Not blocking work, but needs attention
- [ ] Low severity: Needs attention in a timely manner

- [ ] I am unable to use the API
- [ ] I was able to use the API, but am not getting the results I expected
- [ ] I was able to workaround the issue
      

## Steps to reproduce

1. When i am trying to open API, Its showing internal server error.
2. 
3.

**Comment by ryanlink** [comment]
Hi @Kanniga-Git could you please specify which API you're using and the full text of the error response?  Also a cURL command to reproduce the error would be helpful.  You can email api@va.gov for support if that's easier.

**Comment by beaugrantham-va** [comment]
Closing stale issues.
