### ISSUE TITLE
Does the Confirmation API include active personnel?

### ISSUE THREAD

**Issue by colinlieberman** [department-of-veterans-affairs/vets-api-clients#192]
## VA Lighthouse API Documentation Request

Hi there. I'm the developer for a nonprofit looking to offer a military discount. Does the Veteran Confirmation API return a confirmed status for active personnel or only for discharged veterans? If the answer is no, are you able to direct us to an api service that does (and is not a third party service provider)

Thanks

**Comment by Stonelibertyits** [comment]
Good afternoon Colin,

At this time our Confirmation API does provide a status for discharged veterans and does not allow you to verify if the Veteran is active military. You can look into https://www.quandis.com/products/data-services/qms as a possibility to reach your desired outcome.

**Comment by colinlieberman** [comment]
> Good afternoon Colin,
> 
> At this time our Confirmation API does provide a status for discharged veterans and does not allow you to verify if the Veteran is active military. You can look into https://www.quandis.com/products/data-services/qms as a possibility to reach your desired outcome.

Thanks very much, I'll close this issue.
