### ISSUE TITLE
Unexpected not confirmed result in sandbox

### ISSUE THREAD

**Issue by colinlieberman** [department-of-veterans-affairs/vets-api-clients#195]
Hi there, we got a not confirmed result for you from someone we are certain should have been found.

## APIs affected (if applicable)

Confirmation

## How can we help?

For request id 330268b2-4e1f-4b5e-bece-c63ca6658979 in the sandbox environment, we expected a confirmed status for the individual. Are there specific test SSNs etc we're supposed to be using to get confirmed results?

Thanks

**Comment by ryanlink** [comment]
Hi @colinlieberman - we currently do not have documented which of the test users return confirmed and which are not confirmed. I assume the not confirmed users were intended to simulate those with a dishonorable discharge, unless they are meant to be non-veterans. We hope to update the test user documentation page very soon with this info. Please let us know which test user you are authenticating with.

**Comment by colinlieberman** [comment]
Thanks @ryanlink - we were not using pre-defined test users, this was an actual human we were testing with. Could you please point me to the test user documentation? I'm having trouble finding it myself

Thanks
