### ISSUE TITLE
Error when trying to authorize

### ISSUE THREAD

**Issue by lhdmulder** [department-of-veterans-affairs/vets-api-clients#196]
## VA Lighthouse API Bug Report

⚠️ Please read before submitting: As this is a public forum, please do not include any sensitive information (such as your VA API OAuth Client ID, VA API OAuth Client Secret, VA API key, Name, Address, Phone Number, Social Security Number, Medical Record Number, etc). For test apps, please make sure you are using your registered redirect URL, not the URL provided in the example.

## APIs affected (if applicable)

Health API

## API version (if applicable)

DSTU2

## What I expected to happen

Trying to run the oAuth flow for endpoint https://api.va.gov/services/fhir/v0/dstu2, using my redirect link as communicated to you and the clientid as received by you. The URL used (### representing my ClientID):

https://api.va.gov/oauth2/authorization?response_type=code&client_id=#############&redirect_uri=https%3A%2F%2Fmulder.outsystemscloud.com%2FCore%2FAuthorization.aspx&scope=patient/* offline_access launch/patient&state=a4c16a46-2c46-482c-8d66-4cc4a2990bda

I am expecting to see the VA login screen

## What actually happened

Instead of getting an expected User Login screen, I am getting  "An unknown error has occurred"

## Severity of the issue

- [x ] High severity: Blocking work
- [ ] Medium severity: Not blocking work, but needs attention
- [ ] Low severity: Needs attention in a timely manner

- [ ] I am unable to use the API
- [ ] I was able to use the API, but am not getting the results I expected
- [ ] I was able to workaround the issue

**Comment by ryanlink** [comment]
Hi @lhdmulder - apologies for the delayed response but I think you sent this into api@va.gov as well.  Please confirm your issue was resolved.

Thanks,
Ryan Link
Customer Success Manager
API Support Lead, VA Lighthouse API Program

**Comment by beaugrantham-va** [comment]
Closing stale issues.
