### ISSUE TITLE
Would Like to Help Out, How Can I Contribute?

### ISSUE THREAD

**Issue by matthewrmccall** [department-of-veterans-affairs/vets-api-clients#197]
## VA Lighthouse General Feedback

⚠️ Please read before submitting: As this is a public forum, please do not include any sensitive information (such as your VA API OAuth Client ID, VA API OAuth Client Secret, VA API key, Name, Address, Phone Number, Social Security Number, Medical Record Number, etc).

We are continually striving to improve our process and APIs. Your input and feedback ensures we are serving both Veterans and people like you. Thank you!

## Feedback

VA.gov site works well!

**Comment by ryanlink** [comment]
Hi Matthew,

Thanks for your willingness to help. What did you have in mind?

Ryan Link
Customer Success Manager
VA Lighthouse API Program
developer.va.gov
api@va.gov
