### ISSUE TITLE
Error upon connection attempts 

### ISSUE THREAD

**Issue by chuxtones** [department-of-veterans-affairs/vets-api-clients#206]
## VA Lighthouse API Support Request

Error
Your request could not be processed.

Error ID
a18e2690-5775-11eb-a545-c519f557eb03

⚠️ Please read before submitting: As this is a public forum, please do not include any sensitive information (such as your VA API OAuth Client ID, VA API OAuth Client Secret, VA API key, Name, Address, Phone Number, Social Security Number, Medical Record Number, etc). For test apps, please make sure you are using your registered redirect URL, not the URL provided in the example.

**Comment by ryanlink** [comment]
Hi @chuxtones - what were you attempted to do when you received this error?  Please provide steps to reproduce including a curl command of the API request if possible.  Thanks!

**Comment by beaugrantham-va** [comment]
Closing stale issues.
