### ISSUE TITLE
Filtered Facilities does not work

### ISSUE THREAD

**Issue by gclapp** [department-of-veterans-affairs/vets-api-clients#21]
## APIs Affected

v0/facilties

https://dev-api.vets.gov/services/va_facilities/v0/facilities?type=health&page=1&per_page=20

## Brief Summary 

The above call returns zero facilities. It's a cut and paste from the documentation. 

Return value: 

`{"data":[],"links":{"self":"https://dev-api.vets.gov/services/va_facilities/v0/facilities?page=1&per_page=20&type=health","first":"https://dev-api.vets.gov/services/va_facilities/v0/facilities?page=1&per_page=20&type=health","prev":null,"next":null,"last":"https://dev-api.vets.gov/services/va_facilities/v0/facilities?page=1&per_page=20&type=health"},"meta":{"pagination":{"current_page":1,"per_page":20,"total_pages":1,"total_entries":0}}}`

This happens with or without `accept:application/json` being set. 

## Severity of the Issue

Semi-Blocker. 

Here's the workaround I'm going to use (because I don't' want to spend another day on marshaling objects around) - I can call the bounding box version (I have not tried that yet, I hope it works?) and then just pull out the health ones myself. I mean, there is a workaround, but that might not work for other people doing other projects. I can do that because in a 25/50km radius I'm probably only going to get 5-6 so iterating over the whole list isn't the end of the world. But it kinda blows (technically speaking, that is) :) 

## Steps to Reproduce

Call the API on your documentation page or CURL. 

`curl -X GET "https://dev-api.vets.gov/services/va_facilities/v0/facilities?type=health" -H "accept: application/json"`

**Comment by patrickvinograd** [comment]
Just to restate - your proposed workaround is actually the intended semantic of the main query operation  - find facilities within a bounding box, *and* optionally query by type and/or available services - you can do that with the API, you don't have to filter by type yourself. Again, we'll review the API documentation to make sure that's getting across.

**Comment by gclapp** [comment]
@patrickvinograd  Also - should I log a feature request to return an error, or are you tracking those things elsewhere?
