### ISSUE TITLE
Unable to retrieve records.

### ISSUE THREAD

**Issue by ankonaskiff17** [department-of-veterans-affairs/vets-api-clients#217]
## VA Lighthouse API Support Request

⚠️ Please read before submitting: As this is a public forum, please do not include any sensitive information (such as your VA API OAuth Client ID, VA API OAuth Client Secret, VA API key, Name, Address, Phone Number, Social Security Number, Medical Record Number, etc). For test apps, please make sure you are using your registered redirect URL, not the URL provided in the example.

## APIs affected (if applicable)

iBlueButton

**Comment by ryanlink** [comment]
Hi @ankonaskiff17 and thanks for your support request.  We also received your email to api@va.gov and have replied there.  Please contact [iBlueButton support](https://www.ibluebutton.com/contact_us.html) for more info.
