### ISSUE TITLE
Specialty Hours / Closed times for Holidays? 

### ISSUE THREAD

**Issue by gclapp** [department-of-veterans-affairs/vets-api-clients#23]
## APIs Affected

Facility API

## Explanation Feature

This is sort-of related to #20, but that's about the time format - in this case, I'm assuming there are special hours for holidays (either outright closed, like Christmas? Or special holidays like Veterans Day?) - it's unclear how that works. It does not look like the website has support for that either but maybe that will show as we get closer to actual holidays?

## Value Provided by Feature

Right now I could be directing Vets to closed facilities on holidays

## Acceptance Criteria

n/a

**Comment by ryanlink** [comment]
Hi @gclapp -

Thanks very much for using the VA Facilities API, and for your suggestions for improvement.  Apologies for our very delayed response.

With regards to providing exceptions for national holidays and any special hours of operation, if they exist:  Unfortunately we don’t manage the actual data provided for facility hours of operation.  If VA hasn’t included exceptions like that in the data you’re accessing via the API, it won’t be visible to you.

In this case, it’s probably safe to assume the facilities are closed on any federal holidays.  You might want to include a disclaimer on the front-end regarding holidays, or cross-reference this data with a calendar of federal holidays to avoid providing erroneous info.

Having said that, we’d love to know more about your experience with whether holidays are shown as exceptions in the data you retrieve.  If we are able to pass that on to those responsible for managing the data, we will certainly do so.

Much appreciated,

Ryan Link
VA.gov API Developer Support Lead

**Comment by ryanlink** [comment]
P.S. @gclapp - I've been informed that some VA facilities may be open on federal holidays (i.e. emergency rooms).  See https://www.lomalinda.va.gov/about/holiday.asp as an example, but again we unfortunately do not have control over whether VA provides this data to the API.

**Comment by davem-va** [comment]
I have a call with the VAST lead next Monday.  (VAST provides us VHA/health facility info).  I will ask if it's available for those.
