### ISSUE TITLE
Default image of the facilty

### ISSUE THREAD

**Issue by gclapp** [department-of-veterans-affairs/vets-api-clients#24]
## APIs Affected

Facility API 

## Explanation Feature

Would be awesome to get a URL to the image used on VA.gov for the facility, for example, 
https://www.boston.va.gov/locations/Jamaica_Plain_.asp has this image https://www.boston.va.gov/images/jamaicaplain.jpg and the other facilities seem to follow the same method. 

Certainly not urgent, but would be super handy and punch up the UX (cards, on-screen, app) for my apps. 

## Value Provided by Feature

Provide vets with a way to see what the facility looks like, visual consistency with the VA website.

**Comment by ryanlink** [comment]
HI @gclapp - wanted you to know that we are looking into whether we can add this to the API.

We are waiting on some VA decisions right now that are happening around the Facilities API in general, therefore are blocked on this at the moment.  More to come soon.

Thanks,

Ryan Link
Customer Success Manager | Oddball
API Support Lead | Lighthouse VA API Program

Visit developer.va.gov for more on the VA API Program

**Comment by beaugrantham-va** [comment]
Closing stale issues.
