### ISSUE TITLE
Access to Veteran Verification API for shopvcs.com

### ISSUE THREAD

**Issue by robiwon** [department-of-veterans-affairs/vets-api-clients#29]
Please provide the following information

* *Contact Name:* Rob Morrison
* *Contact Email:* rmorrison@govx.com
* *Contact Phone Number:* 858-224-7807
* *Organization Name:* GovX
* *Website:* www.shopvcs.com
* *URL of Privacy Policy:* https://www.shopvcs.com/t/privacy-policy

* [X] Do you agree to the VA API Platform [Terms of Service](https://department-of-veterans-affairs.github.io/vets-contrib/#/explore/terms-of-service) 

### Next Steps

The VA will:
* [ ] Verify this request is made by a US Company
* [ ] Verify that all provided information is accurate
* [ ] Confirm that your privacy policy is understandable by a Veteran using your App or Service
* [ ] View a live demo of your App or Service using the development environment

**Comment by jeff2d2** [comment]
Hello @robiwon,

Can you confirm that you received developer access to this API? You should have received an email noting the next steps, however I wanted to follow up.

Thanks!
