### ISSUE TITLE
Help with General Usage of the Sample Apps 

### ISSUE THREAD

**Issue by JohnnyTest** [department-of-veterans-affairs/vets-api-clients#33]
Hello, There.
I am new to the developer portal, and was trying to run the sample apps provided.  I seem to be stuck at the following points.  I would appreciate any help you could provide.  Thank you.

Using Sample Node.js app
With  Client ID:
0oa3bfyx2nC71Nky62p7

Client Secret:
T9OGW1Xnu-TQ1uCoYCe5yz-XUPZeC--p1IxSZpRh

Result:
http://localhost:8080/auth/cb?error=invalid_client&error_description=The+specified+client+is+not+valid

Error: state missing from the response

*************

Using Sample « Implicit Flow » App - React App
With 
export default {
  oidc: {
    clientId: '0oa3bfyx2nC71Nky62p7',
    issuer: 'https://dev-api.va.gov/oauth2/authorization',
    redirectUri: 'http://localhost:8080/implicit/callback',
    scope: ['openid', 'profile', 'email', 'disability_rating.read', 'service_history.read'],
  },
  resourceServer: {
    serviceHistoryUrl: 'http://localhost:3000/services/veteran_verification/v0/service_history',
    disabilityRatingUrl: 'http://localhost:3000/services/veteran_verification/v0/disability_rating',
  },
};

https://dev-api.va.gov/oauth2/authorization/v1/authorize?client_id=0oa3bfyx2nC71Nky62p7&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fimplicit%2Fcallback&response_type=id_token%20token&response_mode=fragment&state=gJnAWnJMeBjPOlsiaWhSfT2yfSUAMQ2JvaJaXQuoqiWYoGjAbJFjkObPeiYNWOIY&nonce=8j9C3LdDVy41No6XsqZN9UW94QqrXYjgLq0GYia1w1ATjI1TU9gCVy21B1ZMdsaJ&scope=openid%20profile%20email%20disability_rating.read%20service_history.read

Result:
Cannot GET /oauth2/authorization/v1/authorize

**Comment by cychilds** [comment]
Try directing the request to:
https://dev-api.va.gov/oauth2/authorization?string1&string2...etc
