### ISSUE TITLE
Include HoursNote field from VAST in Facility API results

### ISSUE THREAD

**Issue by johnfedwards** [department-of-veterans-affairs/vets-api-clients#35]
## APIs Affected

VA Facilities API

## Explanation Feature

Along with the daily hours returned for a facility, include the HoursNote field from VAST in the results.

## Value Provided by Feature

This would be especially helpful for Medical Centers which are open 24 hours a day but their administrative office is only open during business hours.  That information seems to be available in the HoursNote field of VAST.

**Comment by dhall** [comment]
Thanks for the request John. I'm going to reference this ticket from the internal project our team works from but will update here as we make progress. Please let us know of any other ways this data could be more useful for you!

**Comment by johnfedwards** [comment]
It appears there is information in the HoursNote field that would be beneficial to display to Veterans about access to the facilities on holidays, etc.

**Comment by johnfedwards** [comment]
I believe this field may also go by the name "Operational Hours Special Instructions" as well as "Hours Note"
