### ISSUE TITLE
Missing refresh_token from oauth/token API

### ISSUE THREAD

**Issue by cassiopeiaym** [department-of-veterans-affairs/vets-api-clients#40]
I am following the Authorization Code Flow.
when I call the API about getting token
I have received the result as missing refresh_token, expires_in

1. this is our authorization request : 

https://dev-api.va.gov/oauth2/authorization?client_id=0oa3hkrbd0QG8IY0c2p7&redirect_uri=https://web.samsungphr.com/fhir/oauth/va.html&response_type=code&scope=launch/patient openid profile email veteran_status.read&state=7a99720c4fa90559cfa73494dbbf2abaec803cf2

2. when we can get the 'code'  from redirect page. we call the api to get the tokens.
POST /oauth2/token HTTP/1.1
Host: dev-api.va.gov
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {base64 encoded *client id* + ':' + *client secret*}

grant_type=authorization_code&code={your code}

3. but we can't find the refresh_token and expries_in. we didnot ask the grant type for id_token.
this is our response
 
[{"access_token":"eyJraWQiOiJib2dG*************","token_type":"Bearer","expires_at":1553234539,"scope":"patient/Patient.read launch/patient profile veteran_status.read openid","**id_token**":"eyJraWQiOi*************************","patient":"1017283148V813263","state":"7a99720c4fa90559cfa73494dbbf2abaec803cf2"}] 

Please let me know how to get refresh_token in Authorization Code Flow.

**Comment by dvogel** [comment]
Hi @cassiopeiaym. I'm sorry you're having trouble with this. Luckily the fix should be easy. In order to receive a refresh token, you need to request access to the `offline_access` scope. That's missing from our current documentation. I don't have a great explanation why that's missing but I'm fixing it today. Thanks for helping us find that mistake!

**Comment by cassiopeiaym** [comment]
@dvogel 
Thank you for your guide about this. 

Unfortunately,  I've still not received the keyvalue for 'refresh_token' and 'expires_in' :(
I requsted the scope for these :
> openid profile email offline_access launch/patient patient/Patient.read patient/AllergyIntolerance.read patient/Condition.read patient/DiagnosticReport.read patient/Immunization.read patient/Medication.read patient/MedicationOrder.read patient/MedicationStatement.read patient/Observation.read patient/Procedure.read veteran_status.read

Most of the scopes I knew were requested.

also,  additionally I attached the scope for 'offline_access' you said.
But I couldn't catch the refresh_token and expires_in ~

and I didn't get 'id_token' when I excluded these scopes for 'openid profile'.
But I can't handle the data about refresh_token at all.

Please check your authoriztion code flow and  let me know to get ' refresh_token'.

**Comment by dvogel** [comment]
Hi @cassiopeiaym. There was an additional issue I had to fix with the configuration of your application on our end. Could you try once more?

**Comment by cassiopeiaym** [comment]
@dvogel 
Hi ~ finally I got the refresh_token. 
Of course, I would like you to send me the value of result for **expeirs_in** like as your documents, but I will proceed with offline_access mode with refresh_token and access_token.

**Comment by dvogel** [comment]
I'm glad you were able to get the `refresh_token`. That same payload should have an `expires_at` field. I think there was a typo in the documentation that showed the token payload having an `expires_in` field. We've fixed that in the most recent documentation updates. Please make sure you refresh to receive the most recent documentation. To quickly confirm what you should see:

![screenshot_for_cassiopeiaym](https://user-images.githubusercontent.com/45699/55023444-cf373280-4fca-11e9-9d1b-2a2b758b885b.png)

**Comment by cassiopeiaym** [comment]
@dvogel 
Thank you for everything. :+1: 

I have requested the API for get a new 'refesh_token' now. (grant_type=refresh_token)
and received the same format as when got the access_token payload.

I can calculate the 'expires_in' from decoded 'access_token' data.
Everythins is okay.  

But I have a question about the refresh_token. 
Can I know when the 'refresh_toekn' expires ? or Please Tell me how I can find it .

**Comment by dvogel** [comment]
@cassiopeiaym refresh tokens never expire. We have the ability to revoke them in the event of a security incident but in your development you can assume they are valid.
