### ISSUE TITLE
VA OpenID Connect Authorization Service - grant_type error

### ISSUE THREAD

**Issue by cychilds** [department-of-veterans-affairs/vets-api-clients#44]
⚠️ Please read before submitting: As this is a public forum, please do not include your VA API OAuth Client ID, VA API OAuth Client Secret, VA API key, or any Personally Identifiable Information (PII) or Protected Health Information (PHI) in your report. For test apps, please make sure you are using your registered redirect URL, not the URL provided in the example.

## Email address

<cy@cychilds.com>

## APIs affected (if applicable)

<VA OpenID Connect Authorization Service>

## What I expected to happen

<Receive a token>
1. 
2. 
3. 

## What actually happened

<myserver
  acquires auth2/authorization code "thecode"
  sends POST to https://dev-api.va.gov/oauth2/token
    with query elements
      ?grant_type=authorization_code
      &code=thecode
      &redirect_uri=myserviceuri
    HTTP Headers
      Authorization: Basic myid:mysecret
      Host: dev-api.va.gov
  receives {"error":"unsupported_grant_type","error_description":"Only authorization and refresh_token grant types are supported"}
tried grant_type=authorization_code (as documented) and
grant_type=authorization
same error either way>

## Severity of the issue

- [ ] High severity: Blocking work
- [ ] Medium severity: Not blocking work, but needs attention
- [x ] Low severity: Needs attention in a timely manner

- [x] I am unable to use the API
- [ ] I was able to use the API, but am not getting the results I expected
- [ ] I was able to workaround the issue
      

## Steps to reproduce

1. LAMP ... client browsers Chrome and Firefox on opensuse, android, and windows
2. 
3.

**Comment by dvogel** [comment]
Hi @cychilds, I'm sorry to hear you're having trouble exchanging an authorization code for an access token. The `grant_type=authorization_code` parameter is correct, despite the abbreviated error message. In your post you mentioned query elements. It sounds like you might be including the parameters in the URL rather than in a `application/x-www-form-urlencoded` POST body. Here's a curl command template I use to debug these issues:

```
# Fill in these variables with your registration details:
CLIENT_ID='';
CLIENT_SECRET=''
REDIRECT_URL=''

# Fill in these variables with the values received by your redirect URL:
CODE=''
STATE=''

curl -D- -XPOST "https://dev-api.va.gov/oauth2/token" \
  --basic --user "$CLIENT_ID:$CLIENT_SECRET" \
  -d "grant_type=authorization_code" \
  -d "code=$CODE" \
  -d "state=$STATE" \
  -d "redirect_uri=$REDIRECT_URL"
```

In addition to the redirect URL you registered with, I've added another redirect URL to your application config: `http://localhost:8080/auth/cb`. That should allow you to run our demo app, in case that's helpful to you in your debugging.

**Comment by cychilds** [comment]
Drew,

Nicely done. As you had surmised, I was passing the parameters appended to the auth url as a query string ... thanks for that guidance. I straightened that out and no longer receive the grant_type error.

Unfortunately, I am now getting an "invalid_id" error and I am assuming my "Authorization" HTTP header with the clientid:clientsecret values is malformed. I am simply taking the values sent to me via e-mail when I signed up as a va api developer and assume those values are already base64 encoded. Anyway, I'll play around with that tomorrow.

Thanks again for your help ... very much appreciated. 

Cy

On March 27, 2019 6:58:06 AM PDT, Drew Vogel <notifications@github.com> wrote:
>Hi @cychilds, I'm sorry to hear you're having trouble exchanging an
>authorization code for an access token. The
>`grant_type=authorization_code` parameter is correct, despite the
>abbreviated error message. In your post you mentioned query elements.
>It sounds like you might be including the parameters in the URL rather
>than in a `application/x-www-form-urlencoded` POST body. Here's a curl
>command template I use to debug these issues:
>
>```
># Fill in these variables with your registration details:
>CLIENT_ID='';
>CLIENT_SECRET=''
>REDIRECT_URL=''
>
># Fill in these variables with the values received by your redirect
>URL:
>CODE=''
>STATE=''
>
>curl -D- -XPOST "https://dev-api.va.gov/oauth2/token" \
>  --basic --user "$CLIENT_ID:$CLIENT_SECRET" \
>  -d "grant_type=authorization_code" \
>  -d "code=$CODE" \
>  -d "state=$STATE" \
>  -d "redirect_uri=$REDIRECT_URL"
>```
>
>In addition to the redirect URL you registered with, I've added another
>redirect URL to your application config:
>`http://localhost:8080/auth/cb`. That should allow you to run our demo
>app, in case that's helpful to you in your debugging.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/department-of-veterans-affairs/vets-api-clients/issues/44#issuecomment-477167284


Cy

Cyrus E. Childs
CY CHILDS
1.916.622.9538
www.cychilds.com

**Comment by dvogel** [comment]
@cychilds the credentials you received via email are _not_ base64 encoded. Most HTTP client libraries have support for Basic authentication. There's a good chance you can pass the credentials you received via email to your HTTP client library and it will do the base 64 encoding for you.

In case you can't use an HTTP client library, I can point you toward some lower level documentation. You can see [in this HTTP documentation](https://httpwg.org/specs/rfc7617.html#basic.authentication.scheme) the base64 encoding happens after you concatenate the username and password together. The final header that's sent to the server should look like this (notice the `:` character has been transformed):

```
Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
```

Your best bet is to use an HTTP client library that will handle these details for you, but hopefully that documentation will shed some light on how this is done.

**Comment by cychilds** [comment]
Drew,

Great guidance, once again.

I had just assumed that all three credential elements I received were already base64 encoded ... all three consisting of the base64 character set and each length evenly divisible by 4 (no trailing pads [=]). I encode them as you outlined and all is well. 

Thanks again for all your help ... I hope I wasn't a nuisance. 

Take care.

Cy

Cy

Cyrus E. Childs
CY CHILDS
1.916.622.9538
www.cychilds.com
