### ISSUE TITLE
Getting Internal Server Error on Veteran Verification - Disability Rating API

### ISSUE THREAD

**Issue by stephenmaguire** [department-of-veterans-affairs/vets-api-clients#48]
## APIs affected (if applicable)

Veteran Verification - Disability Rating
https://dev-api.va.gov/services/veteran_verification/v0/disability_rating

## API version (if applicable)

v0

## What I expected to happen

I expect to receive the Veteran's disability rating.

## What actually happened

I am getting a 500 Internal Server Error.

## Severity of the issue

- [ ] High severity: Blocking work
- [ ] Medium severity: Not blocking work, but needs attention
- [X] Low severity: Needs attention in a timely manner
---
- [X] I am unable to use the API
- [ ] I was able to use the API, but am not getting the results I expected
- [ ] I was able to workaround the issue

## Steps to reproduce

1. Authorize using the authorization code flow, and logging in with one of the [test accounts](https://github.com/department-of-veterans-affairs/vets-api-clients/blob/master/test_accounts.md) to get an authorization token
2. Post a GET request on https://dev-api.va.gov/services/veteran_verification/v0/disability_rating with the token from step one

**Comment by Eallan919** [comment]
@stephenmaguire Good morning! Thank you for submitting this ticket.  Our teams worked on it and you should be good to go as it is resolved.  Please reach out if you come across any additional items!

**Comment by stephenmaguire** [comment]
@Eallan919 Perfect, thank you!

**Comment by ryanlink** [comment]
@stephenmaguire would you mind sending an email to api@va.gov referencing this ticket for our records?  Thanks!  


Ryan Link
Customer Success Manager, Oddball
API Support Lead, Lighthouse | VA API Program

Visit developer.va.gov for more on the VA API Program
