### ISSUE TITLE
Facilities/All requesting CSV format throws 500

### ISSUE THREAD

**Issue by jamesperrin** [department-of-veterans-affairs/vets-api-clients#52]
## APIs affected (if applicable)

VA Facilities API

## API version (if applicable)

Version v0

## What I expected to happen

1.  The ability to receive data for all facilities in CSV format.

## What actually happened

Received the following response.

`
{"errors":[{"title":"Internal server error","detail":"Internal server error","code":"500","status":"500"}]}
`

## Severity of the issue

- [ ] High severity: Blocking work
- [X] Medium severity: Not blocking work, but needs attention
- [ ] Low severity: Needs attention in a timely manner

- [ ] I am unable to use the API
- [ ] I was able to use the API, but am not getting the results I expected
- [X] I was able to workaround the issue
      
Work around, obtain data in JSON format, then convert into CSV format.

## Steps to reproduce

1. Send a GET request to https://dev-api.va.gov/services/va_facilities/v0/facilities/all with Accept header of text/csv.

**Comment by ryanlink** [comment]
Hi @jamesperrin - the fix for this has been deployed as of today.  Please let us know if you run into any further issues.  Thanks for submitting, and for your interest in developing for the VA API!

Cheers,

Ryan Link
Customer Success Manager | Oddball.io
Support Portal for VA API Team
developer.va.gov

**Comment by jamesperrin** [comment]
I can confirm, I am able to receive CSV data from the web service endpoint. Thanks.
