### ISSUE TITLE
Document rate limits (if any) for each API.

### ISSUE THREAD

**Issue by ryanlink** [department-of-veterans-affairs/vets-api-clients#55]
## APIs affected (if applicable)

All

## API version (if applicable)

All

## Explanation

Currently there does not appear to be any documentation on rate limits (if they exist) for any of the APIs.

## Link to existing documentation

n/a

## Acceptance criteria
- [ ] Add documentation of rate limits for each API
- [ ] Add links for each API to support FAQ

**Comment by ayaleloehr** [comment]
Not that this is the right place for the documentation or that it's complete, but at the bottom of the Path to Production it does describe rate limits a bit, so could be a starting point: https://developer.va.gov/go-live

**Comment by ryanlink** [comment]
Issue moved to [department-of-veterans-affairs/vets-contrib #1879](https://github.com/department-of-veterans-affairs/vets-contrib/issues/1879) via [**ZenHub**](https://www.zenhub.com/)
