### ISSUE TITLE
Rate limit increase request for VAClaimHelper

### ISSUE THREAD

**Issue by ryanlink** [department-of-veterans-affairs/vets-api-clients#56]
## APIs affected (if applicable)
Benefits Intake

## How can we help?

Stephen (@spardue) from VAClaimHelper.com is requesting a rate limit increase.  He says: 
> The benefits report API keeps on returning a 429. My clients frequently like to check the status of their submissions. Can you increase the rate for my key? 

## What have you tried?
n/a

## Additional context
n/a

**Comment by spardue** [comment]
Hi, for context it is the API at https://developer.va.gov/explore/benefits/docs/benefits
In particular the "/uploads/report" API.

**Comment by ryanlink** [comment]
Issue moved to [department-of-veterans-affairs/vets-contrib #1877](https://github.com/department-of-veterans-affairs/vets-contrib/issues/1877) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ryanlink** [comment]
@spardue I moved this to an internal repo and will get back to you via email with next steps.

**Comment by beaugrantham-va** [comment]
Closing stale issues.
