### ISSUE TITLE
500 when requesting facilities by lat/long and ids

### ISSUE THREAD

**Issue by nfasulo** [department-of-veterans-affairs/vets-api-clients#57]
## APIs affected (if applicable)

Facilities

## What I expected to happen

A request to facilities with lat/long and ids should return the selected facilities in order of distance from the lat/long point.
https://api.va.gov/services/va_facilities/v0/facilities?lat=99.999999&long=-99.999999&page=1&ids=vha_595%2Cvba_460%2Cvha_693%2Cvha_542%2Cvha_460HE%2Cvba_310

## What actually happened

The appeals team identified a new 500 response from the Facilities API that began on Friday in production.
Example:
https://api.va.gov/services/va_facilities/v0/facilities?lat=99.999999&long=-99.999999&page=1&ids=vha_595%2Cvba_460%2Cvha_693%2Cvha_542%2Cvha_460HE%2Cvba_310

## Severity of the issue

- [x] High severity: Blocking work
- [ ] Medium severity: Not blocking work, but needs attention
- [ ] Low severity: Needs attention in a timely manner

**Comment by nfasulo** [comment]
Being fixed with https://github.com/department-of-veterans-affairs/vets-contrib/issues/1915

**Comment by ryanlink** [comment]
@nfasulo was this an externally reported bug?  Anyone I need to communicate to that it's fixed?

**Comment by nfasulo** [comment]
@ryanlink We found out about this bug because the Appeals team reached out to Kalil through [Slack](https://dsva.slack.com/archives/C42P25D6H/p1556491600135000), because he was involved in getting them up and running with the API. He then kept them apprised of the status in the thread as we worked to get the fix out for them.
