### ISSUE TITLE
Add region and parent organization to Facilities listings

### ISSUE THREAD

**Issue by ryanlink** [department-of-veterans-affairs/vets-api-clients#59]
## APIs affected (if applicable)

Facilities

## Explanation

From Tony Diana at VA:

>One piece of information that would be useful would be to add the Region to the listing. So VISN for VHA Facilities, Districts for VBA, etc.

>Beyond that, adding the parent organizations for each would be a huge bonus, to start to show the hierarchy and truly create an organizational unit listing, rather than just a Facility Listing.

**Comment by beaugrantham-va** [comment]
Closing stale issues.
