### ISSUE TITLE
Open ID connect authorization service now unable to find patient

### ISSUE THREAD

**Issue by rockml** [department-of-veterans-affairs/vets-api-clients#60]
Starting last night the authorization step of the Open ID connect is no longer working properly (test sandbox) - the response after sending the authorization code is now always code 400 -
{'error': 'invalid_grant', 'error_description': 'We were unable to find a valid patient identifier for the provided authorization code.'  }
We are using the same code we had been successfully using before.  This is happening for several different sample patients

## APIs affected (if applicable)

Authorization step of Open ID Connect

## What I expected to happen

1. After the user is redirected and authenticates via id.me (sample patients) and the application is redirected back with an authorization code then my application uses the POST method to request an access_token
2. The API returns with a 200 response and an access token
3. 

## What actually happened

The return is a code 400 with the following message:

{'error': 'invalid_grant', 'error_description': 'We were unable to find a valid patient identifier for the provided authorization code.'  }
--

## Severity of the issue

- [xxx] High severity: Blocking work
- [ ] Medium severity: Not blocking work, but needs attention
- [ ] Low severity: Needs attention in a timely manner

- [xxx] I am unable to use the API
- [ ] I was able to use the API, but am not getting the results I expected
- [ ] I was able to workaround the issue
      

## Steps to reproduce

1. Our application is written in python Flask using the flask-oauthlib library
2. 
3.

**Comment by rockml** [comment]
Just noticed it is now suddenly working again. I will keep checking to see if this is intermittent.  Perhaps you were doing some maintenance on the patient database in the test system?

**Comment by ryanlink** [comment]
@rockml This may have been related to some issues we were having with the API Gateway yesterday.  Please keep us posted as to any further errors as they occur!

Ryan Link
Customer Success Manager, Oddball.io
API Support Lead, Lighthouse | VA API Program

Visit developer.va.gov for more on the VA API Program
