### ISSUE TITLE
VBA facilities API on facilities websites

### ISSUE THREAD

**Issue by tadeosss** [department-of-veterans-affairs/vets-api-clients#64]
⚠️ Please read before submitting: As this is a public forum, please do not include any sensitive information (such as your VA API OAuth Client ID, VA API OAuth Client Secret, VA API key, Name, Address, Phone Number, Social Security Number, Medical Record Number, etc).

## APIs affected (if applicable)

N/A, not yet created.

## Explanation

Use the facilities API, the same ones used on va.gov facility locator, to populate facilities information throughout VBA websites and pages. We would like to implement this on our regional offices sites, regional loan centers, intake sites, VR&E offices, and other VBA locations.

## Value provided by feature

Right now, we have the location information manually entered on each of the RO pages and we would like to get away from that so we only have one source of data—the facilities database. 

## Acceptance criteria

Once RO websites are created, its location information (address, phone number, hours of operation, services offered, etc.) should be pulling from an API.

**Comment by ryanlink** [comment]
Pulled this to internal repo and replied to Sandy's email last Thursday.

**Comment by ryanlink** [comment]
Closing this request as there is no action needed by the Lighthouse team.
