### ISSUE TITLE
Benefits intake hitting rate limit while updating statuses en masse?

### ISSUE THREAD

**Issue by ryanlink** [department-of-veterans-affairs/vets-api-clients#69]
This is related to an issue reported where a consumer is not capturing updated statuses from VA:  To update this, what we are finding on our end is that we appear to be hitting the API rate limit.  We are trying to make 20-25 api calls per hour to get updates on upwards of 2000 open items.  It appears that we can only query 100 records at a time.

The result is that the statuses are not getting updated accurately on all claims.  I think this is why our users would see something short of "Complete" despite the fact that the claim is in VBMS already.

The "Validated date" is something we set when we receive either a "Complete" status, or when the submission hits an error.

Do we know what the rate limit is by any chance?

**Comment by dvogel** [comment]
The default rate limit should be 60 requests per minute. Each API response includes headers that indicate how many remaining requests the caller can make before receiving a rate limit error response. For example:

```
X-RateLimit-Limit-Second: 5
X-RateLimit-Remaining-Second: 4
X-RateLimit-Limit-Minute: 10
X-RateLimit-Remaining-Minute: 9
```

**Comment by beaugrantham-va** [comment]
Closing stale issues.
