### ISSUE TITLE
OpenID Connect issues

### ISSUE THREAD

**Issue by ryanlink** [department-of-veterans-affairs/vets-api-clients#72]
## APIs affected (if applicable)

Veteran Verification and Health

From Gil Alterovitz at CIO: 

- After logging in as a veteran via OpenID Connect, there seems to be no way to log out other than entering the browser settings and clearing the history (unlike CMS API). The impact of this is that you cannot test the app as multiple subsequent veterans from the same browser without clearing the cookies. Perhaps recommend that OpenID Connect requires re-authentication or allows one to logout via a link.

- OpenID Connect authentication expires after one hour, and a refresh token is never provided even when the “offline_access” code is requested. The online documentation states that a refresh token will be provided, but this never seems to happen. 

- Occasionally, while in the process of authenticating via OpenID Connect, the VA presents an error page with a reload button. Clicking the reload button normally allows us to proceed without further problems, but something is seems wrong on the VA side.

## Severity of the issue

- [ ] High severity: Blocking work
- [ ] Medium severity: Not blocking work, but needs attention
- [x] Low severity: Needs attention in a timely manner

- [ ] I am unable to use the API
- [ ] I was able to use the API, but am not getting the results I expected
- [x] I was able to workaround the issue

**Comment by ryanlink** [comment]
@bastosmichael reports that logging out has been an issue that we need to address better in the sample apps and documentation. For now, if you go to https://wallet.idmelabs.com you should be able to log yourself out for more testing.

**Comment by beaugrantham-va** [comment]
Closing stale issues.
