### ISSUE TITLE
Unable to request API key

### ISSUE THREAD

**Issue by sparseware** [department-of-veterans-affairs/vets-api-clients#75]
I am unable to request an API key.
I keep getting "We encountered a server error while saving your form. Please try again later."

## What have you tried?
Registering with a different e-mail address and different name (in case the error was due to a name/address collision). 

## Additional context
I had previously registered via a site/page that no longer exist back when you were just getting started (Don DeCoteau).

**Comment by ryanlink** [comment]
Hi @sparseware - have you had any luck trying again since opening this ticket?  Sorry for the delayed response.  

Ryan Link
API Support Lead
Lighthouse | VA API Program
api@va.gov
Visit developer.va.gov for more on the VA API Program

**Comment by sparseware** [comment]
I just tried again, same error

**Comment by ryanlink** [comment]
@sparseware Are you doing this on https://developer.va.gov/apply ?

**Comment by sparseware** [comment]
Yes,
I have attached a pdf of the screen with the message

**Comment by ryanlink** [comment]
Hi @sparseware - sorry but I'm unable to see any attachment.  Please log into the GitHub issue and attach the PDF here rather than sending via email.  Please also provide the exact text you are entering in the fields in that form - alternately you may email these to api@va.gov.

**Comment by ryanlink** [comment]
Don emailed in and I was able to generate OAuth creds for the Health API for him.  Not sure what the issue was, perhaps a proxy, VPN or browser issue preventing form submission.

**Comment by wkarney** [comment]
FWIW I had the same issue while using Safari browser but the form worked fine on Chrome.
