### ISSUE TITLE
Patient API is intermittently returning an error

### ISSUE THREAD

**Issue by rockstreamguy** [department-of-veterans-affairs/vets-api-clients#78]
⚠️ Please read before submitting: As this is a public forum, please do not include any sensitive information (such as your VA API OAuth Client ID, VA API OAuth Client Secret, VA API key, Name, Address, Phone Number, Social Security Number, Medical Record Number, etc). For test apps, please make sure you are using your registered redirect URL, not the URL provided in the example.

Health API (Patient resource)

## API version (if applicable)

test environmetn

## What I expected to happen

1. After OIDC authentication is successful, we can invoke Patient endpoint and get JSON with patient demographic info
2. 
3. 

## What actually happened

We receive the following response (code 200) instead of the patient JSON resource:

'<html><head><title>Request Rejected</title></head><body>The requested URL was rejected.  <br><br>\r\n\r\nThe enhanced features of ServiceNow and Your IT services online requests will replace email requests to the Enterprise Service Desk.  You may access ServiceNow portal at <a href="https://yourit.va.gov">https://yourit.va.gov</a> using the Chrome browser.  The tool is only available from VA workstations and will work with your Personal Identity Verification (PIV) card, eliminating the need for a username and password.  If you have additional questions, please contact Managed Service Providers (MSP) at 1-855-673-4357.\r\n\r\n<br><br>Please make sure to include the entire Support ID number.\r\n\r\n<br><br>Your support ID is: 5891084290371907584<br>Appliance name: gwwlb01-waf-c</body></html>'  

This happens intermittently, but the error occurs more frequently than the correct response

## Severity of the issue

- [x ] High severity: Blocking work
- [ ] Medium severity: Not blocking work, but needs attention
- [ ] Low severity: Needs attention in a timely manner

- [ xx] I am unable to use the API
- [ ] I was able to use the API, but am not getting the results I expected
- [ ] I was able to workaround the issue
      

## Steps to reproduce

1. Python application running Flask web server
2. Tried from both local development machine as well as test environment in AWS
3.

**Comment by ryanlink** [comment]
@rockstreamguy Thank you for reporting this.  We will alert the Health API team and provide next steps shortly.  Could you please email api@va.gov with your information and a link to this GitHub ticket?

Much appreciated,

Ryan Link
Customer Success Manager
API Support Lead, Lighthouse | VA API Program

Visit developer.va.gov for more on the VA API Program

**Comment by ryanlink** [comment]
@rockstreamguy Thanks again for reporting.  We determined that this was due to an outdated URL in your code, perhaps from now-deprecated documentation, referring to dev-api.**vets**.gov rather than dev-api.**va**.gov.  Closing this ticket now.
