### ISSUE TITLE
Implicit Flow Authentication for Single Page or Mobile Applications 

### ISSUE THREAD

**Issue by stcalica** [department-of-veterans-affairs/vets-api-clients#79]
⚠️ Please read before submitting: As this is a public forum, please do not include any sensitive information (such as your VA API OAuth Client ID, VA API OAuth Client Secret, VA API key, Name, Address, Phone Number, Social Security Number, Medical Record Number, etc).

OpenID Connect Authentication API

I am having trouble trying to do a redirection in Javascript. 

```
Your application will need to redirect the Veteran's browser to our OpenID authorization server with a request like this:

HTTP/1.1 302 Found
Location: https://dev-api.va.gov/oauth2/authorize?
  client_id=s6BhdRkqt3
  &response_type=id_token
  &response_mode=fragment
  &redirect_uri=<yourRedirectURL>
  &scope=openid%20profile%20email

```
I try to set `window.location` equal to 
`https://dev-api.va.gov/oauth2/authorize?client_id=<client-ID>&response_type=id_token&response_mode=fragment&redirect_uri=http://firstcivdivcareers.com/clear` in the console to try and replicate it and I recieve a `Cannot GET /oauth2/authorize`

Is it possible to show more documentation for an Implicit flow? 

https://developer.va.gov/explore/verification/docs/authorization

## Acceptance criteria

A small example with vanilla JS to show how a redirect should look and how to authenticate with this path works.

**Comment by stcalica** [comment]
I actually found a sample in the repo. 
However it relies heavily on the  OpenID discovery endpoint and on the library `oidc-client`

While I'd like the docs to show more of it from just a vanilla JS standpoint so I can dissect each call for other JS projects, this will do just fine for now.

Thank you.

**Comment by ryanlink** [comment]
Thanks @stcalica - we will put this in as a user-requested feature and update this ticket with any news.

Ryan Link
Customer Success Manager & API Support Lead
Lighthouse | VA API Program
api@va.gov

Visit developer.va.gov for more on the VA API Program
