### ISSUE TITLE
Veteran Test Data User 

### ISSUE THREAD

**Issue by stcalica** [department-of-veterans-affairs/vets-api-clients#80]
⚠️ Please read before submitting: As this is a public forum, please do not include any sensitive information (such as your VA API OAuth Client ID, VA API OAuth Client Secret, VA API key, Name, Address, Phone Number, Social Security Number, Medical Record Number, etc).

## Explanation

As a non-Veteran developer, I have no idea how to test the application. I did the example authentication flow using `express` however I am not able to get a token cause I have never served. I did create an account using `ID.me` but of course, it returned an issue even though I can log in into ID.me fine on its parent site. 

Error when trying to login: 

[https://imgur.com/LUKt5Qq.jpg](url)

## Value provided by the feature

I would be able to test the functions of a Veteran with history. I'd be able to check status, past records, and etc. without having to be a Veteran. I'd also be able to test my application without a live user. 

## Acceptance criteria

Test data in dev-api.va.gov of a user which I can authenticate and authorize to get test data to test my applications.

**Comment by stcalica** [comment]
Once again, I found it in the [repo](https://github.com/department-of-veterans-affairs/vets-api-clients/blob/master/test_accounts.md)! 
This is information I'd find helpful in the docs on the site. 
But thank you guys!

**Comment by ryanlink** [comment]
Thanks again @stcalica  - will request that this info be copied to the developer portal docs!

**Comment by stcalica** [comment]
Do you have a repo for the portal docs or is that in the vagov-content repo? 
I'd be happy to make those changes for you guys.

**Comment by ryanlink** [comment]
@stcalica Thanks for the offer - the OAuth technical developer portal content is [here](https://github.com/department-of-veterans-affairs/developer-portal/blob/master/src/content/apiDocs/oauthTechnical.mdx).  Much appreciated!
