### ISSUE TITLE
Address Validation

### ISSUE THREAD

**Issue by chprav** [department-of-veterans-affairs/vets-api-clients#86]
## APIs affected (if applicable)

Address Validation AP

https://api.va.gov:8000/address-validation/address/v1/validate

## What I expected to happen

1.  I tested above API from SoapUI 
2) Provided API Key
3. I should get correct address after validation.

## What actually happened

1) I got Connection refused exception

## Severity of the issue

Issue could b
- [ X] High severity: Blocking work
- [ ] Medium severity: Not blocking work, but needs attention
- [ ] Low severity: Needs attention in a timely manner

- [ ] I am unable to use the API
- [ ] I was able to use the API, but am not getting the results I expected
- [ ] I was able to workaround the issue
      

![AddrssValidaionError](https://user-images.githubusercontent.com/54447244/63608141-d3777400-c599-11e9-9b81-1ca4220c71c7.PNG)

**Comment by ryanlink** [comment]
Hi @chprav - thanks for submitting this. Are you using this API internal to the VA network?  It is currently for internal VA use only.

Please send email with your contact info and a link to this issue to api@va.gov.  Thanks,

Ryan Link
Customer Success Manager
API Support Lead, Lighthouse | VA API Program

Visit developer.va.gov for more on the VA API Program

**Comment by beaugrantham-va** [comment]
Closing stale issues.
